# Generated by Django 5.2 on 2025-05-22 21:58

import django.db.models.deletion
import room.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='House, apartment, or building name', max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('colony', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('house_no', models.CharField(max_length=50)),
                ('floor_no', models.CharField(max_length=10)),
                ('has_24h_water', models.BooleanField(default=False)),
                ('has_cold_water', models.BooleanField(default=False)),
                ('has_hot_water', models.BooleanField(default=False)),
                ('separate_bathroom', models.BooleanField(default=False)),
                ('has_rooftop', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('electric_bill_payer', models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner')], max_length=10)),
                ('room_partner_count', models.PositiveIntegerField(default=1)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('1rk', '1RK'), ('1bhk', '1BHK'), ('2bhk', '2BHK'), ('3bhk', '3BHK'), ('hostel', 'Hostel'), ('pg', 'PG'), ('cot', 'Cot-based')], max_length=10)),
                ('advance_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_for', models.CharField(choices=[('boys', 'Boys Only'), ('girls', 'Girls Only'), ('family', 'Family Only'), ('both', 'Both')], max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is the room currently available?')),
                ('image1', models.ImageField(upload_to=room.models.room_image_upload_path)),
                ('image2', models.ImageField(upload_to=room.models.room_image_upload_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=room.models.room_image_upload_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=room.models.room_image_upload_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=room.models.room_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
